In [22]:
import os
os.listdir()

['Music',
 'Guess_the_Dog-HW',
 'temp',
 '.DS_Store',
 '.CFUserTextEncoding',
 'openjdk.jdk',
 'Untitled.ipynb',
 'Pictures',
 '.ipython',
 'Desktop',
 'Library',
 '.lesshst',
 'datac182_hw1_student',
 '.android',
 '.bash_sessions',
 'Public',
 'E-Commerce',
 '.ssh',
 'lab01-checkoff',
 'Movies',
 '.Trash',
 '.ipynb_checkpoints',
 '.jupyter',
 'Documents',
 'cleaned_retail.csv',
 '.swiftpm',
 'Downloads',
 '.python_history',
 '.gitconfig',
 '.bash_history']

## Data Loading

In this step, I load the raw e-commerce dataset and inspect its structure, including available sheets and columns. This helps ensure the data is correctly imported before cleaning and analysis.

In [2]:
import pandas as pd
xls = pd.ExcelFile("E-commerce/online_retail_ii.xlsx")
xls.sheet_names

['Year 2009-2010', 'Year 2010-2011']

In [3]:
df1 = pd.read_excel("E-commerce/online_retail_ii.xlsx", sheet_name=0)
df2 = pd.read_excel("E-commerce/online_retail_ii.xlsx", sheet_name=1)

df = pd.concat([df1, df2], ignore_index=True)

After combining the datasets, I inspect the structure to verify column names, data types, and identify any missing or inconsistent values.

In [5]:
df.shape

(1067371, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 65.1+ MB

In [7]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [9]:
df.columns.tolist()

['Invoice',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'Price',
 'Customer ID',
 'Country']

## Data Cleaning

I prepared the dataset for analysis by removing incomplete and invalid records. Transactions without customer IDs were excluded to enable customer-level analysis, and entries with non-positive quantities or prices were filtered out to ensure accurate revenue calculations and avoid distortion from returns or data errors.

In [13]:
df = df[df["Customer ID"].notna()]
df.shape

(805549, 9)

In [11]:
df = df[df["Quantity"] > 0]
df = df[df["Price"] > 0]

I created additional features to support analysis, including revenue and time-based attributes.

In [15]:
df["Revenue"] = df["Quantity"] * df["Price"]

In [16]:
df["Year"] = df["InvoiceDate"].dt.year
df["Month"] = df["InvoiceDate"].dt.month
df["YearMonth"] = df["InvoiceDate"].dt.to_period("M").astype(str)

In [17]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year,Month,YearMonth
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009,12,2009-12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,2009-12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,2009-12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009,12,2009-12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009,12,2009-12

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 805549 entries, 0 to 1067370
Data columns (total 12 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      805549 non-null  object
 1   StockCode    805549 non-null  object
 2   Description  805549 non-null  object
 3   Quantity     805549 non-null  int64
 4   InvoiceDate  805549 non-null  datetime64[ns]
 5   Price        805549 non-null  float64
 6   Customer ID  805549 non-null  float64
 7   Country      805549 non-null  object
 8   Revenue      805549 non-null  float64
 9   Year         805549 non-null  int32
 10  Month        805549 non-null  int32
 11  YearMonth    805549 non-null  object
dtypes: datetime64[ns](1), float64(3), int32(2), int64(1), object(5)
memory usage: 73.8+ MB

These features enable analysis of revenue trends over time and support aggregation at monthly and yearly levels.

In [19]:
df.shape

(805549, 12)

In [23]:
df.to_csv("E-commerce/cleaned_retail.csv", index=False)

The cleaned dataset was exported for visualization and analysis in Tableau.

In [24]:
os.listdir("E-Commerce")

['Untitled.ipynb',
 'online_retail_II.xlsx',
 '.ipynb_checkpoints',
 'cleaned_retail.csv']